# Generated by Django 2.2 on 2021-06-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_regapp', '0002_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='elo',
            field=models.CharField(default='800', max_length=255),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
