# Generated by Django 2.2 on 2021-06-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_regapp', '0003_auto_20210620_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='region',
            field=models.CharField(default='florida', max_length=255),
        ),
    ]
