# Generated by Django 2.2 on 2021-06-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_regapp', '0004_userreg_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='elo',
            field=models.IntegerField(default=800),
        ),
    ]
