# Generated by Django 2.2 on 2021-06-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_regapp', '0005_auto_20210620_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
